version: '3.8'
services:
  tasker-worker:  
    build:
      context: ./Tasker.Worker 
      dockerfile: Dockerfile
    ports:
      - "5166:8080"
      - "7139:8081"
    restart: always

  tasker-backend:  
    build:
      context: ./Tasker.Backend 
      dockerfile: Dockerfile
    ports:
      - "5165:8080"  
      - "7138:8081"
    restart: always

  tasker-identity:  
    build:
      context: ./Tasker.Identity 
      dockerfile: Dockerfile
    ports:
      - "5154:8080"  
      - "7163:8081"
    restart: always
